### ISSUE TITLE
Unserializing blobs is very slow

### ISSUE THREAD

**Issue by marcboeker** [macks/ruby-protobuf#2]
hi macks,

i've recognized, that ruby-protobuf needs about 58 secs to unserialize a message with one binary filed that has 100mb of data.

unserializing the same data with python takes around 1 second. 

```
$ time ruby binary.rb 

real    0m58.321s
user    0m51.354s
sys     0m1.575s

$ time python binary.py 

real    0m0.817s
user    0m0.248s
sys     0m0.390s
```

this is the protocol i'm using:

```
package foo.bar;
message Message {
    required bytes data = 1;
}
```

let me know if i can help you by providing more data.

thanks in advance,
marc

**Comment by marcboeker** [comment]
hm in 0.4 alpha ruby is faster than python. it only needs 0.5 secs:

```
$ time ruby binary.rb

real    0m0.533s
user    0m0.240s
sys     0m0.256s
```

wow, is version 0.4 on extacy? :) are there any significant changes between 0.3.3 and 0.4 that are responsible for this huge improvement?

thanks and cheers,
marc

**Comment by macks** [comment]
Hi,
Message decoder (deserializer) is optimized in the commit: ca1580d99501e12c81fdd832b92c91babc2b1dd9
Thanks for your report.

**Comment by marcboeker** [comment]
hey,

thanks for your confirmation. from 58 seconds to 0.5 seconds is a damn hot optimization! you should join the formular 1 racing series to optimize their cars :)

thanks for your great work!
cheers marc
